name: Build and deploy Python app to Azure Web App - codincity-logseek01

on:
	@@ -11,8 +15,7 @@ jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
	@@ -23,21 +26,22 @@ jobs:
        run: |
          python -m venv aienv
          source aienv/bin/activate
      - name: Install dependencies
        run: |
          source aienv/bin/activate
          pip install -r requirements.txt

      - name: Zip artifact for deployment
        run: |
          zip -r release.zip . -x 'venv/*'

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip
  deploy:
    runs-on: ubuntu-latest
	@@ -55,10 +59,11 @@ jobs:
      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'codincity-logseek01'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }
